In [12]:
!ls

accuracy	    dataset	      model		       TA-10.ipynb
confusion_matrix    epochTried.ipynb  modelDeploy.ipynb
dataCleaning.ipynb  label	      predictModelInput.ipynb


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
%cd 'drive/MyDrive/TA-10/'

/content/drive/MyDrive/TA-10


In [13]:
import pandas as pd
import tensorflow as tf
from numpy import loadtxt
from keras.models import load_model
from keras.callbacks import EarlyStopping

In [14]:
file = open('dataset/sequences_matrix.csv', 'rb')
sequences_matrix = loadtxt(file,delimiter = ",")
print(sequences_matrix)

[[0.0000e+00 0.0000e+00 0.0000e+00 ... 2.0000e+00 6.0000e+00 1.5000e+01]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 8.4720e+03 1.8000e+01 8.4730e+03]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 8.0000e+00 8.4740e+03 9.0000e+00]
 ...
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 8.0000e+00 2.2651e+04 9.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 2.6000e+01 5.0000e+01 1.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 4.0000e+00 8.4700e+03 8.4700e+03]]


In [15]:
y_train = pd.read_csv('dataset/y_train.csv', index_col = 0, squeeze = True)
print(y_train)

2927     1
16152    1
5659     0
16250    1
11784    0
        ..
11284    0
11964    0
5390     0
860      1
15795    1
Name: Type, Length: 14440, dtype: int64


In [16]:
model = tf.keras.models.load_model('model/lstm_model.h5')

In [17]:
callbacks = EarlyStopping(monitor='val_loss',min_delta=0.0001,patience=3)

In [21]:
history = model.fit(sequences_matrix,y_train,batch_size=128,epochs=50,
          validation_split=0.2,callbacks=[callbacks])

Epoch 1/50
91/91 [==============================] - 19s 204ms/step - loss: 2.7138e-04 - accuracy: 0.9999 - val_loss: 0.0358 - val_accuracy: 0.9907
Epoch 2/50
91/91 [==============================] - 18s 199ms/step - loss: 2.5117e-04 - accuracy: 0.9999 - val_loss: 0.0376 - val_accuracy: 0.9910
Epoch 3/50
91/91 [==============================] - 19s 205ms/step - loss: 2.6070e-04 - accuracy: 0.9999 - val_loss: 0.0371 - val_accuracy: 0.9903
Epoch 4/50
91/91 [==============================] - 18s 202ms/step - loss: 2.4999e-04 - accuracy: 0.9998 - val_loss: 0.0381 - val_accuracy: 0.9910


In [18]:
history = model.fit(sequences_matrix,y_train,batch_size=64,epochs=100,
          validation_split=0.2,callbacks=[callbacks])

Epoch 1/100
181/181 [==============================] - 36s 184ms/step - loss: 0.0046 - accuracy: 0.9995 - val_loss: 0.0278 - val_accuracy: 0.9903
Epoch 2/100
181/181 [==============================] - 24s 134ms/step - loss: 0.0018 - accuracy: 0.9998 - val_loss: 0.0212 - val_accuracy: 0.9920
Epoch 3/100
181/181 [==============================] - 24s 134ms/step - loss: 0.0013 - accuracy: 0.9998 - val_loss: 0.0274 - val_accuracy: 0.9910
Epoch 4/100
181/181 [==============================] - 25s 139ms/step - loss: 0.0010 - accuracy: 0.9999 - val_loss: 0.0255 - val_accuracy: 0.9910
Epoch 5/100
181/181 [==============================] - 25s 136ms/step - loss: 0.0015 - accuracy: 0.9998 - val_loss: 0.0272 - val_accuracy: 0.9907


In [20]:
history = model.fit(sequences_matrix,y_train,batch_size=32,epochs=150,
          validation_split=0.2,callbacks=[callbacks])

Epoch 1/150
361/361 [==============================] - 36s 97ms/step - loss: 6.9160e-04 - accuracy: 0.9998 - val_loss: 0.0273 - val_accuracy: 0.9917
Epoch 2/150
361/361 [==============================] - 36s 99ms/step - loss: 5.7300e-04 - accuracy: 0.9997 - val_loss: 0.0288 - val_accuracy: 0.9913
Epoch 3/150
361/361 [==============================] - 37s 101ms/step - loss: 5.1335e-04 - accuracy: 0.9999 - val_loss: 0.0322 - val_accuracy: 0.9903
Epoch 4/150
361/361 [==============================] - 36s 100ms/step - loss: 4.0584e-04 - accuracy: 0.9999 - val_loss: 0.0351 - val_accuracy: 0.9907


In [ ]:
history = model.fit(sequences_matrix,y_train,batch_size=256,epochs=20,
          validation_split=0.2,callbacks=[callbacks])

Epoch 1/20
46/46 [==============================] - 13s 292ms/step - loss: 5.3865e-04 - accuracy: 0.9998 - val_loss: 0.0367 - val_accuracy: 0.9889
Epoch 2/20
46/46 [==============================] - 13s 282ms/step - loss: 5.4055e-04 - accuracy: 0.9998 - val_loss: 0.0362 - val_accuracy: 0.9893
Epoch 3/20
46/46 [==============================] - 14s 301ms/step - loss: 5.3934e-04 - accuracy: 0.9998 - val_loss: 0.0368 - val_accuracy: 0.9889
Epoch 4/20
46/46 [==============================] - 13s 275ms/step - loss: 5.2597e-04 - accuracy: 0.9998 - val_loss: 0.0370 - val_accuracy: 0.9889
Epoch 5/20
46/46 [==============================] - 12s 261ms/step - loss: 5.0822e-04 - accuracy: 0.9998 - val_loss: 0.0369 - val_accuracy: 0.9889


In [ ]:
history = model.fit(sequences_matrix,y_train,batch_size=512,epochs=15,
          validation_split=0.2,callbacks=[callbacks])

Epoch 1/15
23/23 [==============================] - 10s 433ms/step - loss: 5.0659e-04 - accuracy: 0.9997 - val_loss: 0.0364 - val_accuracy: 0.9896
Epoch 2/15
23/23 [==============================] - 10s 421ms/step - loss: 5.0451e-04 - accuracy: 0.9998 - val_loss: 0.0368 - val_accuracy: 0.9893
Epoch 3/15
23/23 [==============================] - 10s 417ms/step - loss: 5.0135e-04 - accuracy: 0.9998 - val_loss: 0.0368 - val_accuracy: 0.9896
Epoch 4/15
23/23 [==============================] - 10s 451ms/step - loss: 5.0107e-04 - accuracy: 0.9998 - val_loss: 0.0372 - val_accuracy: 0.9889
